# -*- coding: utf-8 -*-
"""yolov7_next_steps.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l90xLpQhGoeutpqNCVKTRL9pDU3Fd3f9
"""

!git clone https://github.com/WongKinYiu/yolov7

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov7

from  hubconf import custom

model = custom(path_or_model='best.pt')

model.eval()

import subprocess

# Command to run detect.py script with specified arguments
command = [
    "python",
    "detect.py",
    "--weights", "best.pt",
    "--conf", "0.5",
    "--source", "/content/yolov7/test-img"
]

# Execute the command
subprocess.run(command)